# Generated by Django 4.0.5 on 2022-07-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_project_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='Design.JPG', null=True, upload_to=''),
        ),
    ]
